### ISSUE TITLE
jar包下载不能

### ISSUE THREAD

**Issue by rekcah1986** [didikee/AndroidDonate#1]
Gradle下载不下来，一直走条

**Comment by didikeeLunaon** [comment]
@rekcah1986  配置了jitpack吗？在项目build.gradle目录下

**Comment by rekcah1986** [comment]
加了

**Comment by didikeeLunaon** [comment]
@rekcah1986 如果你的配置没问题的话就是你的网络问题了
我刚刚测试了是可以下载的
最好可以把你的两个build.gradle文件贴出来看看
